### ISSUE TITLE
How does scorphish determine which version of node to use with nvm?

### ISSUE THREAD

**Issue by andrewpolidori** [oh-my-fish/theme-scorphish#5]
I seem to have an issue where I tell nvm to use an installed version of node

`nvm use 6.11.0`

but the shell continues to use the value that's present in the nvmrc file. 
I can tell that it's using this environment variable 

`function _prompt_nvm -a sep_color -a nvm_color -d "Display current activated Node"
  [ "$theme_display_nvm" != 'yes' -o -z "$NVM_RC_VERSION" ]; and return
  echo -n -s $sep_color '|' $nvm_color $NVM_RC_VERSION
end`

I'm curious as to how that variable actually gets set. Do I have to set it myself?

![screenshot from 2017-07-22 20-30-25](https://user-images.githubusercontent.com/7267450/28495512-d1908c7e-6f1c-11e7-99a0-a0fa0098b2f2.png)

**Comment by scorphus** [comment]
My apologies for the delay in replying. According to creationix/nvm@e7e4a9b, that _env var is unset immediately after it’s no longer needed_. I'll get that fixed. Thanks for reporting ;-)

**Comment by scorphus** [comment]
There you go 🙂  ![image](https://user-images.githubusercontent.com/2112697/28983805-aefcd022-7931-11e7-9b96-09402490addd.png)

**Comment by scorphus** [comment]
@andrewpolidori I am experimenting a bit with some changes, would you try and let me know what you think of them? They're on the [experiments](/oh-my-fish/theme-scorphish/tree/experiments) branch.

Thanks in advance.
